/**
 * In-Memory PLY Store
 *
 * Temporary storage for .ply files generated by SHARP.
 * Stores the binary .ply data plus the source image dimensions
 * so re-renders can match the original aspect ratio.
 *
 * Auto-cleanup: entries expire after 30 minutes of inactivity.
 */

import { randomUUID } from "crypto";

interface StoredPly {
  data: Buffer;
  width: number;
  height: number;
  createdAt: number;
  lastAccessed: number;
}

const plyStore: Map<string, StoredPly> = new Map();

const TTL_MS = 30 * 60 * 1000; // 30 minutes

/**
 * Store a .ply buffer with source image dimensions. Returns unique ID.
 */
export function storePly(data: Buffer, width: number, height: number): string {
  const id = randomUUID();
  const now = Date.now();
  plyStore.set(id, { data, width, height, createdAt: now, lastAccessed: now });
  cleanup();
  return id;
}

/**
 * Retrieve a stored entry by ID. Returns null if not found or expired.
 */
export function getPlyEntry(id: string): { data: Buffer; width: number; height: number } | null {
  const entry = plyStore.get(id);
  if (!entry) return null;

  entry.lastAccessed = Date.now();
  return { data: entry.data, width: entry.width, height: entry.height };
}

/**
 * Retrieve just the .ply buffer by ID (for download endpoint).
 */
export function getPly(id: string): Buffer | null {
  const entry = plyStore.get(id);
  if (!entry) return null;

  entry.lastAccessed = Date.now();
  return entry.data;
}

/**
 * Delete a stored .ply.
 */
export function deletePly(id: string): boolean {
  return plyStore.delete(id);
}

function cleanup(): void {
  const now = Date.now();
  for (const [id, entry] of plyStore) {
    if (now - entry.lastAccessed > TTL_MS) {
      plyStore.delete(id);
    }
  }
}
